用户名: faye.pu
姓名:   蒲若菲
个签:   温柔的女汉子
简介:   

非营利行业从业人员，自由职业设计师。


教育:   None
教育+:  None
行业:   非营利组织
公司:   Golden Bridges
职位:   Director of Operations
提问:   2
回答:   21
被赞同: 350
被感谢: 168
被收藏: 348
收藏夹: 1
关注了: 29
关注者: 153
